import type { components, paths } from "./contract";
export type { paths } from "./contract";

// Entity types
export type Address = components['schemas']['Address']
export type AppointmentDetails = components['schemas']['AppointmentDetails']
export type AppointmentStatus = components['schemas']['AppointmentStatus']
export type AppointmentCreateRequest = components['schemas']['AppointmentCreateRequest']
export type AppointmentUpdateRequest = components['schemas']['AppointmentUpdateRequest']
export type AppointmentBrief = components['schemas']['AppointmentBrief']
export type AppStatus = components['schemas']['AppStatus']
export type Billing = components['schemas']['Billing']
export type BillingStatus = components['schemas']['BillingStatus']
export type ClinicBrief = components['schemas']['ClinicBrief']
export type ClinicDetails = components['schemas']['ClinicDetails']
export type CMSPageContent = components['schemas']['CMSPageContent']
export type Document = components['schemas']['Document']
export type DoctorBrief = components['schemas']['DoctorBrief']
export type DoctorProfile = components['schemas']['DoctorProfile']
export type DoctorPersonalContact = components['schemas']['DoctorPersonalContact']
export type DoctorSpecialty = components['schemas']['DoctorSpecialty']
export type ErrorResponse = components['schemas']['ErrorResponse']
export type LoginRequest = components['schemas']['LoginRequest']
export type Language = components['schemas']['Language']
export type MedicalTreatment = components['schemas']['MedicalTreatment']
export type Notification = components['schemas']['Notification']
export type NotificationListItem = components['schemas']['NotificationListItem']
export type OpeningHours = components['schemas']['OpeningHours']
export type PatientBrief = components['schemas']['PatientBrief']
export type PatientProfile = components['schemas']['PatientProfile']
export type PrescribedTreatment = components['schemas']['PrescribedTreatment']
export type PrescribedTreatmentStatus = components['schemas']['PrescribedTreatmentStatus']
export type Referral = components['schemas']['Referral']
export type ReferralStatus = components['schemas']['ReferralStatus']
export type ReferralCreateRequest = components['schemas']['ReferralCreateRequest']
export type ReferralUpdateRequest = components['schemas']['ReferralUpdateRequest']
export type RegisterRequest = components['schemas']['RegisterRequest']
export type ServiceType = components['schemas']['ServiceType']
export type ServiceOffer = components['schemas']['ServiceOffer']
export type Coordinates = components['schemas']['Coordinates']
