openapi: '3.0.0'
info:
  title: Medical Centre API
  version: '1.0.0'
  description: API for managing medical appointments

servers:
  - url: 'http://localhost:3001/api'
    description: Local development server

paths:
  /appointments:
    get:
      summary: Get all appointments
      description: Retrieve a list of all appointments
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
    post:
      summary: Create a new appointment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppointmentCreate'
      responses:
        '201':
          description: Appointment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'

  /appointments/{appointmentId}:
    put:
      summary: Update an appointment
      parameters:
        - name: appointmentId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppointmentUpdate'
      responses:
        '200':
          description: Appointment updated successfully
    delete:
      summary: Delete an appointment
      parameters:
        - name: appointmentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Appointment deleted successfully

  /referrals:
    post:
      summary: Create a new referral
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReferralCreate'
      responses:
        '201':
          description: Referral created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Referral'

  /referrals/{referralId}:
    put:
      summary: Update a referral
      parameters:
        - name: referralId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReferralUpdate'
      responses:
        '200':
          description: Referral updated successfully
    delete:
      summary: Delete a referral
      parameters:
        - name: referralId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Referral deleted successfully

components:
  schemas:
    Appointment:
      type: object
      properties:
        id:
          type: string
          format: uuid
        patientId:
          type: string
        doctorId:
          type: string
        date:
          type: string
          format: date-time
        status:
          type: string
          enum: [SCHEDULED, COMPLETED, CANCELLED]
        notes:
          type: string
      required:
        - id
        - patientId
        - doctorId
        - date
        - status
    AppointmentCreate:
      type: object
      properties:
        patientId:
          type: string
        doctorId:
          type: string
        date:
          type: string
        time:
          type: string
        description:
          type: string
      required:
        - patientId
        - doctorId
        - date
        - time

    AppointmentUpdate:
      type: object
      properties:
        date:
          type: string
        time:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [SCHEDULED, COMPLETED, CANCELLED]

    Referral:
      type: object
      properties:
        id:
          type: string
        patientId:
          type: string
        issuingDoctorId:
          type: string
        targetSpeciality:
          type: string
        diagnosis:
          type: string
        recommendations:
          type: string
        issueDate:
          type: string
        expiryDate:
          type: string
        status:
          type: string
          enum: [ACTIVE, USED, EXPIRED]
      required:
        - id
        - patientId
        - issuingDoctorId
        - targetSpeciality
        - diagnosis
        - recommendations
        - issueDate
        - expiryDate
        - status

    ReferralCreate:
      type: object
      properties:
        patientId:
          type: string
        targetSpeciality:
          type: string
        diagnosis:
          type: string
        recommendations:
          type: string
        expiryDate:
          type: string
      required:
        - patientId
        - targetSpeciality
        - diagnosis
        - recommendations
        - expiryDate

    ReferralUpdate:
      type: object
      required:
        - referralId
        - status
      properties:
        referralId:
          type: string
          format: uuid
          description: The ID of the referral to update
        status:
          type: string
          enum: [ACTIVE, USED, EXPIRED]
